"""
    This file belongs to the Project ESP-ToDoViewer-MSToDo
    Copyright (c) 2023 Peter Tißen
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

import datetime
import subprocess

def create_version_file():
    try:
        filename = "version.h"
        
        with open(filename, 'w', encoding='utf-8') as file:
            t = datetime.datetime.now()
            datestring = t.strftime("%d-%b-%Y (%H:%M:%S)")
            version = subprocess.run('git describe --always --long --tags --dirty', stdout=subprocess.PIPE, shell=True, check=True)
            author = subprocess.run("git log -1 --pretty=format:\"%an\"", stdout=subprocess.PIPE, shell=True, check=True)

            file.write(f"// File automatically generated by createVersionHeader.py")
            file.write(f"\n// File created on: {datestring} \n")
            file.write(f"\n#pragma once")
            file.write(f"\n#define VERSION_INFO   \"{version.stdout.decode().strip()}\"")
            file.write(f"\n#define VERSION_AUTHOR \"{author.stdout.decode().strip().replace('.', ' ')}\"")
            file.write(f"\n#define VERSION_COMPILATION_DATE __date__")
            file.close()
            
    except (FileNotFoundError, subprocess.CalledProcessError) as e:
        print(f"Error creating version file: {str(e)}")

create_version_file()
